# CODE FROM SCRATCH

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\Users\LOQ\Desktop\Machine Learning\Linear Regression\data\raw\placement.csv')
data.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [3]:
X = data.iloc[:,:1].values
y = data.iloc[:,1:2].values


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 2)

In [5]:
class MYLR:
    def __init__(self):
        self.m = None
        self.b = None
    def fit(self,X_train,y_train):
        num = 0 
        den = 0
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i]- y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)
    def predict(self,X_test):
        return self.m * X_test + self.b

In [6]:
lr = MYLR()

In [7]:
lr.fit(X_train,y_train)

[0.55795197]
[-0.89611192]


In [8]:
X_train.shape[0]

160

In [9]:
X_train.mean()

np.float64(6.989937500000001)

In [12]:
X_test[0]

array([8.58])

In [13]:
y_test[0]

array([4.1])

In [14]:
lr.predict(X_test[0])

array([3.89111601])